language: android
jdk: oraclejdk8
sudo: required

before_cache:
- rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock
- rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
- rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/gradle/caches/
  - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-google-m2repository
  - ndk-bundle

env:
  global:
  - DIR=apng-drawable
  - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"

before_install:
- echo 'count=0' > /home/travis/.android/repositories.cf

jobs:
  include:
  - stage: Prepare libpng
    script: "cd ${TRAVIS_BUILD_DIR} && cat libpng_version | xargs ./download_libpng_and_apply_apng_patch.sh"
  - stage: Build
    script: "cd ${TRAVIS_BUILD_DIR} && ./gradlew assembleDebug"
  - stage: Test
    script: "cd ${TRAVIS_BUILD_DIR} && ./gradlew :apng-drawable:testDebugUnitTest :apng-drawable:lint :apng-drawable:ktlintCheck"
  - stage: deploy
    script: 'deploy'

#before_script:
#- export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
#- cd ${TRAVIS_BUILD_DIR} && cat libpng_version | xargs ./download_libpng_and_apply_apng_patch.sh
#
#script:
#- cd ${TRAVIS_BUILD_DIR} && ./gradlew assembleDebug :apng-drawable:testDebugUnitTest :apng-drawable:lint :apng-drawable:ktlintCheck
#
#after_script:
#- cat ${TRAVIS_BUILD_DIR}/${DIR}/*/build/reports/lint-results.xml
